### ISSUE TITLE
Remove sqlite3 from default import

### ISSUE THREAD

**Issue by RangerMauve** [martinheidegger/hyper-dns#14]
It's been really hard to get stuff working cross platform while better-sqlite3 is in the dependency tree since it doesn't have prebuilds the way other native dependencies in the hyper stack do.

It'd be nice if this dependency could be marked as optional or opt-in to unblock development.

**Comment by martinheidegger** [comment]
I quickly threw something together in 3e94410 - let me know if this works for you.

Sidenote: It looks like there is an issue on better-sqlite to use prebuildify https://github.com/JoshuaWise/better-sqlite3/issues/655
